# Certbot configuration
# Store all certs and config in /persistent
config-dir = /persistent/seismic-ssl/letsencrypt/config
work-dir = /persistent/seismic-ssl/letsencrypt/work
logs-dir = /persistent/seismic-ssl/letsencrypt/logs
