{
 "title": "Summit",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summit handle proposal duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal start building block duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_start_building_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_start_building_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal compute digest duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_compute_digest_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_compute_digest_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal get payload duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_get_payload_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_get_payload_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal finalizer notification duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_finalizer_wait_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_finalizer_wait_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal aux data wait duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_aux_data_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_aux_data_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle verify duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(rate(seismic_bft_handle_verify_duration_micros_sum[5m]) / rate(seismic_bft_handle_verify_duration_micros_count[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit handle proposal parent fetch duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(seismic_bft_handle_proposal_parent_fetch_duration_millis_sum[5m]) / rate(seismic_bft_handle_proposal_parent_fetch_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true
  },
  {
   "title": "Summit checkpoint creation duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(seismic_bft_checkpoint_creation_duration_millis_sum[1h]) / rate(seismic_bft_checkpoint_creation_duration_millis_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit current block processing time [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(seismic_bft_total_block_processing_duration_millis_sum[5m]) / rate(seismic_bft_total_block_processing_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit blocks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "rate(seismic_bft_blocks_committed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit average time between blocks [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "1 / rate(seismic_bft_blocks_committed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit finalizer database operations duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "rate(seismic_bft_database_operations_duration_millis_sum[5m]) / rate(seismic_bft_database_operations_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit total handle execution block duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "rate(seismic_bft_total_block_processing_duration_millis_sum[5m]) / rate(seismic_bft_total_block_processing_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit Payload Check [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "rate(seismic_bft_payload_check_duration_millis_sum[5m]) / rate(seismic_bft_payload_check_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit parse execution requests duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "rate(seismic_bft_parse_execution_requests_duration_millis_sum[5m]) / rate(seismic_bft_parse_execution_requests_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit average block time [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "rate(seismic_bft_block_time_millis_sum[5m]) \n  / rate(seismic_bft_block_time_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit block size (transactions per block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "(rate(seismic_bft_tx_committed_total[2m]) / rate(seismic_bft_blocks_committed_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit block processing time 1 hour ago [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "(rate(seismic_bft_total_block_processing_duration_millis_sum[5m] offset 1h) / rate(seismic_bft_total_block_processing_duration_millis_count[5m] offset 1h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit process execution requests duration [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "rate(seismic_bft_process_execution_requests_duration_millis_sum[5m]) / rate(seismic_bft_process_execution_requests_duration_millis_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summit Finalitzer Checkpoint Size [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "rate(seismic_bft_checkpoint_size_bytes_sum[5m]) / rate(seismic_bft_checkpoint_size_bytes_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Syncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Syncer DB operations (metadata) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"metadata\"}[5m]) / \n  rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"metadata\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered success rate (notarized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivered_total{type=\"notarized\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered success rate (finalized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "100 * rate(seismic_bft_syncer_block_delivered_total{type=\"finalized\"}[5m]) / \n  (rate(seismic_bft_syncer_block_delivered_total{type=\"finalized\"}[5m]) +\n  rate(seismic_bft_syncer_block_delivery_failed_total{type=\"finalized\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered success rate (block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "targets": [
    {
     "expr": "  100 * rate(seismic_bft_syncer_block_delivered_total{type=\"block\"}[5m]) / \n  (rate(seismic_bft_syncer_block_delivered_total{type=\"block\"}[5m]) + \n  rate(seismic_bft_syncer_block_delivery_failed_total{type=\"block\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivery failed total (notarized, validation_failed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivery_failed_total{type=\"notarized\", reason=\"validation_failed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivery failed total (notarized, decode_error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivery_failed_total{type=\"notarized\", reason=\"decode_error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivery failed total (finalized, validation_failed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivery_failed_total{type=\"finalized\", reason=\"validation_failed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivery failed total (finalized, decode_error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivery_failed_total{type=\"finalized\", reason=\"decode_error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivery failed total (block, commitment_mismatch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivery_failed_total{type=\"block\", reason=\"commitment_mismatch\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered total (notarized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivered_total{type=\"notarized\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered total (finalized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivered_total{type=\"finalized\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block delivered total (block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_delivered_total{type=\"block\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch duration average (notorized) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 267 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_fetch_duration_millis_sum{type=\"notarized\"}[5m]) / \n  rate(seismic_bft_syncer_block_fetch_duration_millis_count{type=\"notarized\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch duration average (finalized) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 275 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_block_fetch_duration_millis_sum{type=\"finalized\"}[5m]) / \n  rate(seismic_bft_syncer_block_fetch_duration_millis_count{type=\"finalized\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch duration average (block) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 283 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_block_fetch_duration_millis_sum{type=\"block\"}[5m]) / \n  rate(seismic_bft_syncer_block_fetch_duration_millis_count{type=\"block\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch duration (notarized) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(seismic_bft_syncer_block_fetch_duration_millis_bucket{type=\"notarized\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch duration (finalized) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 299 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(seismic_bft_syncer_block_fetch_duration_millis_bucket{type=\"finalized\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer average block fetch duration (block) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 307 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_block_fetch_duration_millis_sum{type=\"block\"}[5m]) / \n  rate(seismic_bft_syncer_block_fetch_duration_millis_count{type=\"block\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch request total (subscribe)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_fetch_requests_total{type=\"subscribe\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch request total (finalized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_fetch_requests_total{type=\"finalized\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (cache_finalizations) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"cache_finalizations\"}[5m]) /   rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"cache_finalizations\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (cache_notorizations) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"cache_notarizations\"}[5m]) /\n  rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"cache_notarizations\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (cache_notorized) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"cache_notarized\"}[5m]) /   rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"cache_notarized\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (cache_verified) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"cache_verified\"}[5m]) /\n  rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"cache_verified\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (finalizations) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 363 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"finalizations\"}[5m]) / \n  rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"finalizations\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer DB operations (finalized_blocks) [millis]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
   "targets": [
    {
     "expr": "  rate(seismic_bft_syncer_storage_operation_duration_millis_sum{archive=\"finalized_blocks\"}[5m]) /\n  rate(seismic_bft_syncer_storage_operation_duration_millis_count{archive=\"finalized_blocks\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer block fetch request total (notarized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 379 },
   "targets": [
    {
     "expr": "rate(seismic_bft_syncer_block_fetch_requests_total{type=\"notarized\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 387 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reth blocks per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 388 },
     "targets": [
      {
       "expr": "rate(reth_sync_execution_execution_histogram_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth transactions per second (derived from total transactions executed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 396 },
     "targets": [
      {
       "expr": "rate(reth_sync_execution_transactions_executed_total[1m]) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth gas per second (1m average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 404 },
     "targets": [
      {
       "expr": "avg_over_time(reth_sync_execution_gas_per_second[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth transactions executed total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 412 },
     "targets": [
      {
       "expr": "reth_sync_execution_transactions_executed_total{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth transactions per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 420 },
     "targets": [
      {
       "expr": "reth_sync_execution_transactions_per_second{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth transactions per second (1m average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 428 },
     "targets": [
      {
       "expr": "avg_over_time(reth_sync_execution_transactions_per_second[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth histogram tracking block execution duration (secs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 436 },
     "targets": [
      {
       "expr": "reth_sync_execution_execution_histogram",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reth gas per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 444 },
     "targets": [
      {
       "expr": "reth_sync_execution_gas_per_second",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}