# One pin builds BOTH seismic-enclave-server and tdx-init. We could consider
# using separate pins for each, but this is simpler for now, plus they will
# likely need to be updated together in most cases since they will share libraries.
enclave:
  git_reference: 4fa1b5f18425696b4cb5587606632ba909c4ee4c
seismic_reth:
  git_reference: 4bbc6502ea566171decc97adc0c39106967e5ad9
summit:
  git_reference: ed2c5c844e9ec40884ddc72fc16ece36b7d99a56
