[Content]
ExtraTrees=mkosi.extra
KernelCommandLine=console=tty0 console=ttyS0,115200n8 mitigations=auto,nosmt spec_store_bypass_disable=on nospectre_v2 intel_iommu=on

Packages=udev
         nvme-cli
         xxd
