[Build]
Environment=KERNEL_CONFIG_SNIPPETS=seismic/kernel.config,mkosi.profiles/gcp/kernel.config

[Content]
SandboxTrees=mkosi.sandbox
ExtraTrees=mkosi.extra
SkeletonTrees=mkosi.skeleton

Packages=udev
         nvme-cli
         xxd
         google-guest-agent
         google-compute-engine
         dmsetup
