[Build]
Environment=KERNEL_CONFIG_SNIPPETS=seismic/kernel.config,mkosi.profiles/gcp/kernel.config

[Content]
ExtraTrees=mkosi.extra

Packages=udev
         nvme-cli
         xxd
         google-guest-agent
         google-compute-engine-oslogin
         dmsetup
