[Output]
ImageId=seismic

[Build]
Environment=LIGHTHOUSE_BINARY KERNEL_CONFIG_SNIPPETS=seismic/kernel.config KERNEL_VERSION=6.13.12
WithNetwork=true

[Content]
ExtraTrees=seismic/mkosi.extra
PostInstallationScripts=seismic/mkosi.postinst
BuildScripts=seismic/mkosi.build

Packages=openntpd
         nginx
         certbot
         python3-certbot-nginx
         libtss2-esys-3.0.2-0t64
         libtss2-tctildr0t64
         jq

BuildPackages=build-essential
              git
              gcc
              curl
              zlib1g-dev
              libzstd-dev
              libleveldb-dev
              libsnappy-dev
              libpq-dev
              libssl-dev
              libtss2-dev
              pkg-config
