[Output]
ImageId=seismic

[Build]
Environment=SUMMIT_BINARY SEISMIC_RETH_BINARY ENCLAVE_BINARY KERNEL_CONFIG_SNIPPETS=seismic/kernel.config KERNEL_VERSION=6.13.12
WithNetwork=true

[Content]
ExtraTrees=seismic/mkosi.extra
PostInstallationScripts=seismic/mkosi.postinst
BuildScripts=seismic/mkosi.build

Packages=openntpd
         tpm2-tools
         tpm2-abrmd
         libtss2-esys-3.0.2-0
         libtss2-tcti-device0
         libtss2-tcti-mssim0
         nginx
         certbot
         python3-certbot
         python3-certbot-nginx

BuildPackages=build-essential
              git
              gcc
              curl
              cargo
              rustc
              zlib1g-dev
              libzstd-dev
              libleveldb-dev
              libsnappy-dev
              libpq-dev
              libssl-dev
              protobuf-compiler
              libprotobuf-dev
              pkg-config
              clang
              libtss2-dev
